It runs!!
Angular2 compiled & ran!

This error still happens but good enough for now!
angular2-polyfills.js:349 Error: Error: XHR error (404 Not Found)
loading http://localhost:3001/app/bootstrap.js

Also added lite-server because visual studio has a bug with node or
something so it doesnt always run...   so npm start to the rescue! I
think lite-server is redudant though.

Oh well,  cleanup next then make the angular app!